# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Jointeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_point', models.IntegerField(default=0)),
                ('point_2', models.IntegerField(default=0)),
                ('point_3', models.IntegerField(default=0)),
                ('free_throw', models.IntegerField(default=0)),
                ('rebound', models.IntegerField(default=0)),
                ('foul', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('play_time', models.IntegerField(default=0)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('profile_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ama', 'amateur'), ('uni', 'university')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('from_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team_id', to='club.Team')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Position')),
                ('to_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team_id', to='club.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Position'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Team'),
        ),
        migrations.AddField(
            model_name='performance',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Player'),
        ),
        migrations.AddField(
            model_name='performance',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Position'),
        ),
        migrations.AddField(
            model_name='match',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Season'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_id', to='club.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_id', to='club.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_id', to='club.Team'),
        ),
        migrations.AddField(
            model_name='jointeam',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Season'),
        ),
        migrations.AddField(
            model_name='jointeam',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('match_id', 'player_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='jointeam',
            unique_together=set([('season_id', 'team_id')]),
        ),
    ]
